### PR TITLE
Add support for continuous integration via travis

### PR DESCRIPTION
**Pull request by jchodera**
This adds continuous integration support via travis.

### CODE REVIEW

**Comment by jchodera** [comment]
I think travis is working now!

There are some failures due to python 3.x issues that are addressed separately in #3

**Comment by jchodera** [comment]
To save time in future travis runs, we can cache the equilibrium data using [this scheme](https://docs.travis-ci.com/user/caching/#Caching-directories-(Bundler%2C-dependencies)).

**Comment by jchodera** [comment]
This is going to be super useful in debugging #3, so I'd suggest merging this PR first and then merging the latest changes into #3 when you pick things up again.

**Comment by maxentile** [comment]
Ahh, thanks for putting this together! Just looked over all the changes, and they look good to me. Will make a couple minor edits to Yank-specific devtools files, then merge. I'm a bit puzzled by some of the Travis failures (e.g. [`No module named 'numpy'`](https://travis-ci.org/choderalab/integrator-benchmark/jobs/222472546#L624)), but will look into this later...

>To save time in future travis runs, we can cache the equilibrium data using this scheme. We'd probably want to make it possible to override DATA_PATH by an environment variable $BENCHMARK_DATA_PATH so that we can cache the data in $HOME/data instead.

Good idea! Will add an Issue to remind me to do this...

**Pull request merged**
