### PR TITLE
Add readme, double-well testsystem, and minor updates

### PR DESCRIPTION
**Pull request by maxentile**
* Incorporates the velocity-sampling fix from: https://github.com/choderalab/integrator-benchmark/pull/17
* Adds a draft readme outlining the project
* Refactors the low-dimensional test systems / integrators so that the quartic potential isn't hardcoded, adds a 1D double-well test system
* Fixes the BAOAB vs. VVVR comparison script (`O V R R V O` =/= `O V R V O` when there are constraints)

### CODE REVIEW

**Comment by jchodera** [comment]
@maxentile : I noticed the travis tests had been killed, so I retriggered them.

The python 3.6 test failed, so I created PR #19 into your `double-well` branch to fix them.

**Comment by maxentile** [comment]
Ahh, thanks! I had manually cancelled the Travis tests because they also time-out on the equilibrium sampling step -- I still need to flag some tests as slow / have Travis cache the equilibrium samples...

**Comment by jchodera** [comment]
I've created PR #20 to reduce the number of equilibrium samples generated by travis.

**Comment by jchodera** [comment]
It still might be useful to move to lazy sample generation at some point...

**Comment by maxentile** [comment]
Woohoo, Travis is finally happy -- merging

**Pull request merged**
